spring.application.name=EmployeeSystem
spring.datasource.url=jdbc:mysql://localhost:3306/employee
spring.datasource.username=root
spring.datasource.password=@sam8079
spring.jpa.hibernate.ddl-auto=update
server.port=7070